### PR TITLE
Specify default charset for string and byte calls

### PR DESCRIPTION
**Pull request by timja**
Fixes CI / spotbugs

### CODE REVIEW

**Comment by timja** [comment]
hmm ok, archiving artifacts is an issue, plugin-installation-manager-tool has an hpi for some reason somewhere i guess.

any suggestions @oleg-nenashev ?

**Comment by oleg-nenashev** [comment]
Created https://github.com/jenkinsci/lib-crypto-util/pull/9

**Comment by timja** [comment]
> Maybe it is better to keep using the system default charset to avoid regressions when reading old keys.

the key format is USASCII from what I can tell but comments can be in utf-8 format, couldn't see any harm in this

**Comment by oleg-nenashev** [comment]
What if the original file was saved in another encoding which does not directly map to URF-8, e.g. [CP-1251](https://en.wikipedia.org/wiki/Windows-1251) which many of my colleagues cordially hate? Forcing UTF-8 will cause issues in such case

**Pull request merged**
