### PR TITLE
Fix MIT license URL

### PR DESCRIPTION
**Pull request by darxriggs**

### CODE REVIEW

**Comment by darxriggs** [comment]
@jenkinsci/code-reviewers can you have a look at this?

**Comment by darxriggs** [comment]
Can you also merge it and prepare a new release?
That's required for the correct license information to be shown in the Jenkins UI.

**Comment by oleg-nenashev** [comment]
This library is a part of the Jenkins core, so I have made a bold assumption that @jenkinsci/core owns the repository. I have configured the permissions accordingly. The component has not been released since 2014, and it will require some time to fix the release flow and update the component to get it out. Even CI is not configured as you may see.

@darxriggs could you please create a Jira issue for this problem?

**Comment by timja** [comment]
Unit tests fail on my machine with no changes, FML

**Comment by darxriggs** [comment]
@oleg-nenashev I guess your request to create a Jira issue is already obsolete after you and @timja brought this plugin into shape again. Thank you very much.

**Pull request merged**
